### PR TITLE
Rsb/cogs

### PR DESCRIPTION
**Pull request by richardphi1618**
refactored bot to use the cogs framework detailed by discords documentation.

### CODE REVIEW

**Comment by Chris-May** [comment]
I just checked out this PR and noticed a few concerns. They might not have to do with this PR specifically, but I figure I can note them here.

- The tests fail with the message `ModuleNotFoundError: No module named 'raffle_bot'`.
- I can't find anything that declares what dependencies this project has.

This is not to heap criticism on the work done. I appreciate the help and would be happy to help with them.

**Comment by richardphi1618** [comment]
yea that was an old test from main and how Cohan started. Probably should revisit how tests are built for this project but I ultimately don't know how we would do tests on a project like this. Maybe each cog needs to be tested as independent functions.... Iono tests were low on the list of figuring out how the "discord bot" works. 

I think a conversation would need to happend for me to best explain what I am saying... sorry if I am not making sense.

**Comment by richardphi1618** [comment]
> I just checked out this PR and noticed a few concerns. They might not have to do with this PR specifically, but I figure I can note them here.
> 
> * The tests fail with the message `ModuleNotFoundError: No module named 'raffle_bot'`.
> * I can't find anything that declares what dependencies this project has.
> 
> This is not to heap criticism on the work done. I appreciate the help and would be happy to help with them.

I think we should just delete the tests and perform the merge. I am working on a refactor at the moment moving away from discord.py ( I think is stale) to the much more maintained and active pycord. Please let me know how to make this happen.

**Comment by Chris-May** [comment]
I added a few commits to give class names TitleCase, format files, add one test, and add dependency information.

**Comment by richardphi1618** [comment]
branch is dead per the following Chris found:

@everyone v2.1 has been released on PyPI.

Important

If you're not using v2, this is a reminder that your bot will stop working by the end of the year unless you update. Discord is going to remove v7 and below at the end of the year, which v1.7.3 and below use. Please update and migrate to v2 as soon as possible.
THat's from the discord.py server

**Pull request closed without merging**
